# -*- coding: utf-8 -*-
"""deploy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sk7UFIMQ8tN2w8KwGN43PdazP_qjNBj5
"""

import joblib

# Load the Scikit-learn model
model = joblib.load('/content/sample_data/modo.joblib')

# Define a function that takes user input and returns a predicted price
def predict_price(lot_area, overall_cond, year_sold):
    input_array = [[lot_area, overall_cond, year_sold]]
    predicted_price = model.predict(input_array)[0]
    return predicted_price

import streamlit as st

# Import your machine learning model here
# ...

st.title("House Price Predictor")

# Get user input using Streamlit widgets
lot_area = st.number_input("Lot area of the house (in square feet)", value=1000)
overall_cond = st.slider("Overall condition of the house (1-10)", min_value=1, max_value=10, value=7)
year_sold = st.number_input("Year the house was sold", value=2010)

# Make a prediction using the machine learning model
prediction = model.predict([[lot_area, overall_cond, year_sold]])

# Print the prediction to the Streamlit app
st.write(f"Predicted price of the house: ${prediction[0]:,.2f}")

!streamlit run /usr/local/lib/python3.9/dist-packages/ipykernel_launcher.py --server.fileWatcherType none