# -*- coding: utf-8 -*-
"""housetheprice_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15RT3zKZl0NuwV74V55qR9CXPXoxGgFgP
"""

import pandas as pd 
import numpy as np
d = pd.read_csv('/content/sample_data/train.csv')
d_frame=pd.DataFrame(d)

d_frame.columns  
#d_frame.head

from sklearn.tree import DecisionTreeRegressor as reg
import joblib
li=['LotArea','OverallCond','YrSold']
x=d_frame[li]
print(x)
Y=d_frame.SalePrice



p_model=reg()
p_model.fit(x,Y)
rdi=p_model.predict(x)
rdi_d=pd.DataFrame(rdi)
rdi_d.to_csv('mypred_train.csv')
print(rdi_d)

import matplotlib.pyplot as plt 

plt.scatter(rdi,Y)



d_test = pd.read_csv("/content/sample_data/test.csv")
d_frame_test=pd.DataFrame(d_test)
#d.head
#d.describe
d_test.columns
#d_frame.SalePrice false

li_test=['LotArea','OverallCond','YrSold']
x_test=d_frame_test[li_test]





t_res=p_model.predict(x_test)
print(t_res)
t_frame=pd.DataFrame(t_res)
t_frame.to_csv('test_pred.csv')

def inputter(lot,overalc,yrsol) :
    i=np.array([[lot,overalc,yrsol]])
    fin=p_model.predict(i)
    print("your house price $ ",fin)

a=int(input("enter lot area : "))
b=int(input("enter the overall condition of the plot : " ))
c=int(input("enter the year sold or finished :  " ))
inputter(a,b,c)